name: Feature Suggestion
description: Suggest a feature
body:
  - type: markdown
    attributes:
      value: |
        # Octopus AI: Feature Suggestion
        Thanks for taking the time to provide a feature suggestion!
        
        While the solutions engineering team will make a reasonable effort to respond to this request, Octopus AI has no Support Level Agreement (SLA).

  - type: textarea
    id: feature
    attributes:
      label: Feature
      description: What would you like to see added to Octopus AI
      placeholder: Provide a feature suggestion
    validations:
      required: true

